import type { LandingPageLayout, LandingPageElement } from '../../../types.js';

export const DEFAULT_HERO_IMAGE = '/farhan_hero_portrait.jpg';

export const createDefaultLandingPageElements = (): LandingPageElement[] => [
  {
    id: 'elem-bg-glow',
    name: 'Gold Background Ambient Glow',
    type: 'decorative_shape',
    shapeType: 'glow',
    backgroundColor: '#e5a93c',
    color: '#e5a93c',
    locked: false,
    order: 1,
    desktop: {
      x: 880,
      y: 120,
      width: 440,
      height: 520,
      visible: true,
      opacity: 0.12,
      rotation: 0,
      zIndex: 1,
      borderRadius: 9999
    },
    tablet: {
      x: 180,
      y: 90,
      width: 400,
      height: 400,
      visible: true,
      opacity: 0.1,
      rotation: 0,
      zIndex: 1,
      borderRadius: 9999
    },
    mobile: {
      x: 20,
      y: 80,
      width: 350,
      height: 350,
      visible: true,
      opacity: 0.08,
      rotation: 0,
      zIndex: 1,
      borderRadius: 9999
    }
  },
  {
    id: 'elem-geom-frame',
    name: 'Geometric Frame Accent',
    type: 'decorative_shape',
    shapeType: 'frame',
    borderColor: '#e5a93c',
    borderWidth: 2,
    borderStyle: 'solid',
    locked: false,
    order: 2,
    desktop: {
      x: 905,
      y: 135,
      width: 360,
      height: 460,
      visible: true,
      opacity: 0.85,
      rotation: 0,
      zIndex: 2,
      borderRadius: 16
    },
    tablet: {
      x: 190,
      y: 90,
      width: 388,
      height: 400,
      visible: true,
      opacity: 0.8,
      rotation: 0,
      zIndex: 2,
      borderRadius: 16
    },
    mobile: {
      x: 20,
      y: 85,
      width: 350,
      height: 350,
      visible: true,
      opacity: 0.7,
      rotation: 0,
      zIndex: 2,
      borderRadius: 16
    }
  },
  {
    id: 'elem-hero-image',
    name: 'Hero Profile Image',
    type: 'image',
    imageUrl: DEFAULT_HERO_IMAGE,
    imageAlt: 'Farhan Tasneem - CSE Student & Developer',
    imageCrop: 'cover',
    imagePosition: 'center top',
    borderColor: '#2e3544',
    borderWidth: 1,
    borderStyle: 'solid',
    locked: false,
    order: 3,
    desktop: {
      x: 920,
      y: 150,
      width: 330,
      height: 430,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 3,
      borderRadius: 16
    },
    tablet: {
      x: 204,
      y: 105,
      width: 360,
      height: 370,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 3,
      borderRadius: 16
    },
    mobile: {
      x: 35,
      y: 100,
      width: 320,
      height: 320,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 3,
      borderRadius: 16
    }
  },
  {
    id: 'elem-floating-badge',
    name: 'BUILD · LEARN · CREATE Badge',
    type: 'badge',
    content: 'BUILD · LEARN · CREATE',
    backgroundColor: '#12151b',
    borderColor: '#2e3544',
    borderWidth: 1,
    color: '#e5a93c',
    iconName: 'Sparkles',
    locked: false,
    order: 4,
    desktop: {
      x: 935,
      y: 535,
      width: 300,
      height: 44,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 2,
      textAlign: 'center',
      visible: true,
      opacity: 0.95,
      rotation: 0,
      zIndex: 4,
      borderRadius: 12
    },
    tablet: {
      x: 234,
      y: 435,
      width: 300,
      height: 40,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 2,
      textAlign: 'center',
      visible: true,
      opacity: 0.95,
      rotation: 0,
      zIndex: 4,
      borderRadius: 12
    },
    mobile: {
      x: 45,
      y: 380,
      width: 300,
      height: 40,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.5,
      textAlign: 'center',
      visible: true,
      opacity: 0.95,
      rotation: 0,
      zIndex: 4,
      borderRadius: 12
    }
  },
  {
    id: 'elem-eyebrow',
    name: 'HELLO, I\'M Eyebrow',
    type: 'text',
    content: "HELLO, I'M",
    color: '#9ca3af',
    textTransform: 'uppercase',
    locked: false,
    order: 5,
    desktop: {
      x: 100,
      y: 135,
      width: 400,
      height: 30,
      fontSize: 13,
      fontWeight: '600',
      letterSpacing: 3,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 5
    },
    tablet: {
      x: 50,
      y: 510,
      width: 400,
      height: 28,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 3,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 5
    },
    mobile: {
      x: 20,
      y: 445,
      width: 350,
      height: 26,
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 2,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 5
    }
  },
  {
    id: 'elem-heading-first',
    name: 'FARHAN Headline',
    type: 'heading',
    content: 'FARHAN',
    color: '#ffffff',
    textTransform: 'uppercase',
    locked: false,
    order: 6,
    desktop: {
      x: 100,
      y: 170,
      width: 650,
      height: 75,
      fontSize: 72,
      lineHeight: 1.05,
      fontWeight: '800',
      letterSpacing: -1,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 6
    },
    tablet: {
      x: 50,
      y: 540,
      width: 668,
      height: 56,
      fontSize: 52,
      lineHeight: 1.05,
      fontWeight: '800',
      letterSpacing: -1,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 6
    },
    mobile: {
      x: 20,
      y: 475,
      width: 350,
      height: 48,
      fontSize: 42,
      lineHeight: 1.05,
      fontWeight: '800',
      letterSpacing: -0.5,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 6
    }
  },
  {
    id: 'elem-heading-accent',
    name: 'TASNEEM Accent Headline',
    type: 'heading',
    content: 'TASNEEM',
    color: '#e5a93c',
    textTransform: 'uppercase',
    locked: false,
    order: 7,
    desktop: {
      x: 100,
      y: 245,
      width: 650,
      height: 75,
      fontSize: 72,
      lineHeight: 1.05,
      fontWeight: '800',
      letterSpacing: -1,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 7
    },
    tablet: {
      x: 50,
      y: 596,
      width: 668,
      height: 56,
      fontSize: 52,
      lineHeight: 1.05,
      fontWeight: '800',
      letterSpacing: -1,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 7
    },
    mobile: {
      x: 20,
      y: 523,
      width: 350,
      height: 48,
      fontSize: 42,
      lineHeight: 1.05,
      fontWeight: '800',
      letterSpacing: -0.5,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 7
    }
  },
  {
    id: 'elem-subtitle',
    name: 'Professional Title',
    type: 'text',
    content: 'Computer Science & Engineering Student',
    color: '#d1d5db',
    locked: false,
    order: 8,
    desktop: {
      x: 100,
      y: 335,
      width: 650,
      height: 35,
      fontSize: 20,
      fontWeight: '600',
      letterSpacing: 0,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 8
    },
    tablet: {
      x: 50,
      y: 660,
      width: 668,
      height: 30,
      fontSize: 18,
      fontWeight: '600',
      letterSpacing: 0,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 8
    },
    mobile: {
      x: 20,
      y: 580,
      width: 350,
      height: 30,
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0,
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 8
    }
  },
  {
    id: 'elem-description',
    name: 'Hero Description',
    type: 'text',
    content:
      'Motivated Computer Science and Engineering student at Daffodil International University with a strong academic background, passion for artificial intelligence, prompt engineering, and software development.',
    color: '#9ca3af',
    locked: false,
    order: 9,
    desktop: {
      x: 100,
      y: 380,
      width: 620,
      height: 80,
      fontSize: 15,
      lineHeight: 1.6,
      fontWeight: '400',
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 9
    },
    tablet: {
      x: 50,
      y: 700,
      width: 668,
      height: 70,
      fontSize: 14,
      lineHeight: 1.5,
      fontWeight: '400',
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 9
    },
    mobile: {
      x: 20,
      y: 620,
      width: 350,
      height: 95,
      fontSize: 13,
      lineHeight: 1.5,
      fontWeight: '400',
      textAlign: 'left',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 9
    }
  },
  {
    id: 'elem-feature-strip',
    name: 'Feature Highlight Strip',
    type: 'feature_strip',
    items: [
      { id: 'f1', label: 'AI Prompt Engineering', icon: 'Sparkles' },
      { id: 'f2', label: 'GPA 5.00 College & School', icon: 'Award' },
      { id: 'f3', label: 'Bangla • English • Hindi', icon: 'Languages' },
      { id: 'f4', label: 'Problem Solver', icon: 'Lightbulb' }
    ],
    backgroundColor: '#141822',
    borderColor: '#222938',
    color: '#d1d5db',
    accentColor: '#e5a93c',
    locked: false,
    order: 10,
    desktop: {
      x: 100,
      y: 475,
      width: 650,
      height: 42,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 10
    },
    tablet: {
      x: 50,
      y: 785,
      width: 668,
      height: 42,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 10
    },
    mobile: {
      x: 20,
      y: 730,
      width: 350,
      height: 80,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 10
    }
  },
  {
    id: 'elem-btn-primary',
    name: 'View My Work Button',
    type: 'button',
    content: 'View My Work',
    buttonVariant: 'primary',
    buttonAction: 'view_work',
    backgroundColor: '#e5a93c',
    color: '#0c0e12',
    iconName: 'ArrowRight',
    locked: false,
    order: 11,
    desktop: {
      x: 100,
      y: 545,
      width: 175,
      height: 48,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 11,
      borderRadius: 8
    },
    tablet: {
      x: 50,
      y: 845,
      width: 170,
      height: 46,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 11,
      borderRadius: 8
    },
    mobile: {
      x: 20,
      y: 825,
      width: 350,
      height: 48,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 11,
      borderRadius: 8
    }
  },
  {
    id: 'elem-btn-secondary',
    name: 'Download CV Button',
    type: 'button',
    content: 'Download CV',
    buttonVariant: 'secondary',
    buttonAction: 'download_cv',
    backgroundColor: '#12151b',
    borderColor: '#2e3544',
    borderWidth: 1,
    color: '#f3f4f6',
    iconName: 'Download',
    locked: false,
    order: 12,
    desktop: {
      x: 290,
      y: 545,
      width: 175,
      height: 48,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 12,
      borderRadius: 8
    },
    tablet: {
      x: 235,
      y: 845,
      width: 170,
      height: 46,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 12,
      borderRadius: 8
    },
    mobile: {
      x: 20,
      y: 885,
      width: 350,
      height: 48,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 12,
      borderRadius: 8
    }
  },
  {
    id: 'elem-social-links',
    name: 'Social Channels Row',
    type: 'social_links',
    color: '#9ca3af',
    borderColor: '#1f2533',
    items: [
      { id: 's1', label: 'GitHub', platform: 'GitHub', url: 'https://github.com' },
      { id: 's2', label: 'LinkedIn', platform: 'LinkedIn', url: 'https://linkedin.com' },
      { id: 's3', label: 'Fiverr', platform: 'Fiverr', url: 'https://fiverr.com' },
      { id: 's4', label: 'Facebook', platform: 'Facebook', url: 'https://facebook.com' },
      { id: 's5', label: 'Instagram', platform: 'Instagram', url: 'https://instagram.com' }
    ],
    locked: false,
    order: 13,
    desktop: {
      x: 100,
      y: 620,
      width: 400,
      height: 44,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 13
    },
    tablet: {
      x: 50,
      y: 910,
      width: 400,
      height: 42,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 13
    },
    mobile: {
      x: 20,
      y: 950,
      width: 350,
      height: 44,
      visible: true,
      opacity: 1,
      rotation: 0,
      zIndex: 13
    }
  }
];

export const createDefaultLandingPageLayout = (): LandingPageLayout => ({
  id: 'layout-primary',
  version: 1,
  canvasHeightDesktop: 780,
  canvasHeightTablet: 980,
  canvasHeightMobile: 1040,
  backgroundColor: '#0c0e12',
  elements: createDefaultLandingPageElements(),
  updatedAt: new Date().toISOString()
});

export const defaultLandingPageLayout = createDefaultLandingPageLayout();

